# Generated by Django 4.2.3 on 2023-08-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='user_first_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
