# Generated by Django 4.2.3 on 2023-08-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_rename_name_movie_title_movie_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
