create table names (name varchar(255), id integer primary key);
insert into names (name) values ('first line');
insert into names (name) values ('second line');
select name from names;
alter table names rename to mainnames;
select name from mainnames;
alter table mainnames add column age;
alter table mainnames add column id;
select name, age from mainnames;
insert into mainnames (name, age) values ('third line');
select name, age from mainnames;
update mainnames set age = 2 where id = 2;
delete from mainnames where id = 2;