numer1 = int(input("write first number: "))
numer2 = int(input("write second number: "))
print("Result: ", numer1 + numer2)
print("Result: ", numer1 - numer2)
print("Result: ", numer1 * numer2)
print("Result: ", numer1 / numer2)